### ISSUE TITLE
fully qualified urls

### ISSUE THREAD

**Issue by mnichols** [bleupen/halacious#45]
Thanks for this great lib! 
Are you writing utilities to provide fully qualified urls inside your _links ? If so, how are you doing so with the generated curies `href` urls? Are you relying on downstream fiddling of the urls to mint them properly?

So instead of 

```js
{
    _links: {
        self: { href: '/api' }
        , curies: [ { name: 'foo', href: '/rels/Foo/{rel}' }]
}
```

Client really should be seeing

```js

{
    _links: {
        self: { href: 'https://myhost.com/api' }
       , curies: [ { name: 'foo', href: 'http://developer.foo.com/rels/Foo/{rel}' }]
    }
}
```

**Comment by bleupen** [comment]
hello!

now that the holidays are behind me, I finally have some time to devote to this library. I think this should be pretty easy to do via configuration parameter.

**Comment by bleupen** [comment]
if you have a chance, please take a look at the change I just pushed up to master. You can set an "absolute" configuration property to true on the route or as a global halacious plugin option.

**Comment by mnichols** [comment]
I thought I responded to this but my reply seemed to disappear. I'll repost:

This is a step in the right direction but won't help when hosting the server behind a proxy (host/ports will differ from the 'server' setup). Ideally a pluggable strategy (callback) for calculating the URL could be provided so that an environment variable or other config could be read to generate the urls found in the payload. 
This is simple enough as a little utility method in the `_links` for resources, but the curie href generation doesnt seem to provide a way to modify it.
I'll poke into it this week and try to produce a PR for your review.

**Comment by dminkovsky** [comment]
Yes, thank you for this. Maybe also something like inspecting an incoming request's `x-forwarded-host`, etc headers. I've seen that the Spring HATEOAS module [does this](https://github.com/spring-projects/spring-hateoas/blob/bf9584f91ede3f89c4e602b68a4682917fd231be/src/main/java/org/springframework/hateoas/mvc/ControllerLinkBuilder.java#L185-L229).

**Comment by gavriguy** [comment]
+1
