### ISSUE TITLE
Halacious causes hapi to set an undefined HTTP location header

### ISSUE THREAD

**Issue by alanbrown** [bleupen/halacious#46]
Under certain circumstances Halacious seems to cause Hapi to set an HTTP header with a value of undefined. With node 0.12 this causes an exception to be thrown because of this change (from what I can tell) https://github.com/joyent/node/commit/979d0ca874df0383311ca06f154f6965074196ee which looks legitimate to me. The  Error('"name" and "value" are required for setHeader().') is the case which is triggered, and some minor hacking indicates this is related to the HTTP location field.

Using curl as below

    $ curl -i http://localhost:8080/api/

calling the following code

    'use strict';

    var     hapi = require('hapi');

    var server = new hapi.Server();
    server.connection({
        host: '0.0.0.0',
        port: 8080,
    });

    server.route({
        method: 'get',
        path: '/test',
        config: {
            handler: function (req, reply) {
                reply('hello, world');
            }
        }
    });

    server.register({
        register: require('halacious'),
        options: {apiPath: '/api'}
    }, function (err) {
       if (err) throw err;

        var ns = server.plugins.halacious.namespaces.add({
                name: 'acano',
                description: 'Acano Corningstone API',
                prefix: 'acano'
        });
        ns.rel({
            name: 'provisioningcert',
            description: 'A provision certificate'
        });

        server.start(function (err) {
            if (err) throw err;

            console.log('Server started...');
        });
    });

causes the issue to manifest for me as 

    Debug: internal, implementation, error 
        Error: "name" and "value" are required for setHeader().
        at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
        at Object.internals.transmit (/home/vagrant/hapi-test/node_modules/hapi/lib/transmit.js:250:25)
        at /home/vagrant/hapi-test/node_modules/hapi/lib/transmit.js:34:26
        at Function.internals.Auth.response (/home/vagrant/hapi-test/node_modules/hapi/lib/auth.js:381:16)
        at /home/vagrant/hapi-test/node_modules/hapi/lib/transmit.js:139:25
        at internals.Response._streamify (/home/vagrant/hapi-test/node_modules/hapi/lib/response.js:484:12)
        at internals.Response._marshal (/home/vagrant/hapi-test/node_modules/hapi/lib/response.js:433:21)
        at /home/vagrant/hapi-test/node_modules/hapi/lib/transmit.js:119:18
        at /home/vagrant/hapi-test/node_modules/hapi/lib/transmit.js:535:20
        at Object.exports.parallel (/home/vagrant/hapi-test/node_modules/hapi/node_modules/items/lib/index.js:47:9)

In case its relevant

    $ uname -a
    Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bleupen** [comment]
Thanks for looking into this. I'll try to reproduce it today.

**Comment by bleupen** [comment]
this is fixed with version 3.0.1
