### ISSUE TITLE
"absolute" configuration not updating links in api catalog

### ISSUE THREAD

**Issue by travi** [bleupen/halacious#54]
While some links are getting updated to be absolute, the ones that are added to the automatically generated root, by adding the `api` route configuration, don't seem to get updated.

**Comment by bleupen** [comment]
Thanks I'll take a look

**Comment by bleupen** [comment]
i pushed a fix for this. would it be possible for you to test your configuration against the master branch before i issue a release?

thanks!

**Comment by travi** [comment]
@bleupen sure thing. I updated to master and it looks like it took care of my issue. Thanks a lot for the quick response.

**Comment by bleupen** [comment]
thanks for testing that out! I just published version 3.1.2.
