### ISSUE TITLE
pass uri template through on href object 

### ISSUE THREAD

**Issue by lsnyder** [bleupen/halacious#55]
Hey guys,

New to hypermedia, so please inform me if this usecase is ridiculous, but I have a situation where I'd like to pass the uri template I'm attaching to the href all the way through to the response without it being expanded. Once my object hits resolveHref() my template gets expanded into and empty string and I lose the template. 
This is desired result:
```
/call/123876213876{?id}
```
Gets nuked to this
```
/call/123876213876
```

The reason I want the template to pass through is because these links will not always appear on a route that requires the actual {id} parameter to be passed in. In this case I'd like the api consumer to be aware of the possible routes they can hit if they supply the paremeters specified in the uri template.

**Comment by bleupen** [comment]
Hi there,

Yes, this is tougher than it should be. Lately, I have been using hapi 8 route id's to resolve a lot of my links. This has the side benefit of preserving the route's query parameters. See if this works for you (off the top of my head so there are probably syntax errors):

```javascript
server.route({
   path: '/api/widgets',
   method: 'get',
   config: {
      handler: function(req, reply) {},
      plugins: {
          hal: {
              api: 'mco:widgets',
              query: '{?size,limit,q}' // will be appended to references to this route,
              embedded: {
                 'mco:widget': {
                     path: 'items',
                     href: function(rep, ctx) {
                        // the route function will locate the named route, resolve parameters via the context, and append the route's query params. 
                        return rep.route('widget.lookup', ctx.item); 
                     }
                 }
              } 
          }
      }
   }
});

server.route({
   path: '/api/widgets/{id}',
   method: 'get',
   config: {
      id: 'widget.lookup',
      handler: function(req, reply) {},
      plugins: {
          hal: {
              api: 'mco:widget',
              query: '{?profile}' // will be appended to references to this route
          }
      }
   }
});
```

**Comment by lsnyder** [comment]
Was able to get desired results. Thanks @bleupen!
