### ISSUE TITLE
No way to add an empty array of links

### ISSUE THREAD

**Issue by brabster** [bleupen/halacious#56]
I'd like to be able to represent an empty array of links - for example, a link rel 'items' that connects a resource to 0..* items.

I'd like to guarantee that there will always be an 'items' property present in the _links map, and that it will contain an empty array if there are no 'items' links.

Halacious errors if I do: `rel.link('items', [])`, but it's fine for `rel.link('items', ['./items/1'])` and `rel.link('items', ['./items/1', './items/2'])`.

Is there a reason this isn't supported? I imagine it's an oversight rather than by design, as it'd be easy to accidentally wind up with an empty array there.

**Comment by bleupen** [comment]
I think originally empty arrays were intentionally being excluded from the representation to make client parsing easier. This feature led to a regression at some point. I have checked in a fix to master. Let me know if it is working for you.

**Comment by brabster** [comment]
Works a treat!

Thanks very much - very helpful library and blown away by the speed of response.

Haven't done this before; I have a private build of halacious' master HEAD right now - I guess I can swap that out when you next publish to npm? Do you have any idea when this change will be available through public npm?

Thanks again!

**Comment by bleupen** [comment]
Great!

I just pushed a new patch release 3.1.3.

**Comment by brabster** [comment]
Fantastic. Thanks very much.
