### ISSUE TITLE
Categorize links inside _links object

### ISSUE THREAD

**Issue by lsnyder** [bleupen/halacious#57]
I would like to throw my analytics links into a bucket within the _links object called "analytics", is this achievable? Currently i'm loading in links like we discusses in issue #55  Thanks!

Current:
```
_links: {
self: {
  href: "/phonesheets/{?Id}"
},
  calls-per-day: {
     href: "/analytics/calls-per-day{?Id}",
     templated: true
   },
    keywords: {
      href: "/analytics/keywords{?Id}",
      templated: true
    },
    last-contact: {
      href: "/analytics/last-contact{?Id}",
      templated: true
    }
}
```

Desired:
```
_links: {
self: {
  href: "/phonesheets/{?Id}"
},
analytics: {
  calls-per-day: {
     href: "/analytics/calls-per-day{?Id}",
     templated: true
   },
    keywords: {
      href: "/analytics/keywords{?Id}",
      templated: true
    },
    last-contact: {
      href: "/analytics/last-contact{?Id}",
      templated: true
    }
  }
}
```

**Comment by bleupen** [comment]
@lsnyder were you able to resolve this issue?

**Comment by lsnyder** [comment]
I've since moved on to some other stuff, but when I left off with this I was still unable to figure out the best way to achieve the above result. Any suggestions would be appreciated!

**Comment by brabster** [comment]
Hi @lsnyder,

I think what you're suggesting would deviate from the draft HAL spec at https://tools.ietf.org/html/draft-kelly-json-hal-06, which would make this plugin incompatible with any strict HAL clients.

If I were you and I wanted this feature, I'd engage with the author of the spec with this suggestion to see if the spec should include it - then this lib and others can support the new feature interoperably.

I'd argue to close off this request until the spec reflects the feature?

**Comment by lsnyder** [comment]
Sounds good @brabster. I will take a look at the spec and see if this sort of functionality has a place. Thanks!
