### ISSUE TITLE
Empty embedded arrays should be preserved

### ISSUE THREAD

**Issue by bleupen** [bleupen/halacious#58]
Unlike links, empty embedded arrays are currently stripped from the response. Fix to make consistent with links.

**Comment by brabster** [comment]
I'm not sure how to use this when I have an array of items that I want to embed that have different links, say I have an array of objects like `{id: 1, name: 'Bob'}` (different IDs) and I want to embed these objects such that I get:

```
_embedded: {
  friends: [
    {
      _links: { self: { href: '/people/1' } },
      name: 'Bob'
    },
    ...
  ]
}
```

I can't see how to use this feature to embed where the hrefs will be different, possibly also complicated by the fact that I want to omit the property that gets used in building the self href for each one.

Have I missed something?
