### ISSUE TITLE
protocol for absolute links incorrect when hosted from https

### ISSUE THREAD

**Issue by travi** [bleupen/halacious#61]
As I mentioned in #60, absolute links do not include the correct protocol when the api is served from https. 

I have not spent significant time investigating if this is even possible to detect at the server level, but thought it would be valuable to log this to give visibility to the issue. 

If not possible to detect on the server, is there at least a way to configure `halacious` to make absolute links use `https` as the protocol that I'm overlooking?

**Comment by travi** [comment]
Was this closed on purpose? Was something changed to fix this?

**Comment by bleupen** [comment]
The newest release supports hardwiring protocol, hostname, and port via plugin config params. You may also set a urlBuilder for complete control of absolute link urls.

**Comment by travi** [comment]
Great, thanks!
