### ISSUE TITLE
3.3.1 - relsAuth and apiAuth should not be validated as Joi.boolean

### ISSUE THREAD

**Issue by spanditcaa** [bleupen/halacious#69]
auth in hapi is either false for unauthenticated, or an object such as ````{ strategies: [ 'session' ] }````.

**Comment by spanditcaa** [comment]
I'll PR shortly.

**Comment by spanditcaa** [comment]
see https://github.com/bleupen/halacious/pull/70

**Comment by bleupen** [comment]
Fixed, thank you! And apologies for the regression.

**Comment by spanditcaa** [comment]
np, thanks Brad.
