### ISSUE TITLE
Issues with URIjs

### ISSUE THREAD

**Issue by clcpolevaulter** [bleupen/halacious#85]
I am unable to use halacious@3.0.1. It is requiring in [URI.js](https://github.com/medialize/URI.js). [URI.js](https://github.com/medialize/URI.js) changed their [npm registration](https://www.npmjs.com/package/URIjs) to `urijs`. halacious is requiring in as `URIjs` in https://github.com/bleupen/halacious/blob/master/lib/representation.js#L6.

```
Error: Cannot find module 'URIjs'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/app/current/node_modules/our-app/node_modules/server-framework/node_modules/halacious/lib/representation.js:6:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by bleupen** [comment]
My apologies. Not sure how that one got by. I just published a 3.5.1 patch release. Does that fix your issue?

**Comment by clcpolevaulter** [comment]
I am trying now. I am curious if https://github.com/bleupen/halacious/blob/master/lib/representation.js#L6 needs to be updated as well. I will let you know how that worked.

**Comment by bleupen** [comment]
omg complete screw up on my end. pushing the wrong branch. hold tight..

**Comment by bleupen** [comment]
Ok should be good to go.

**Comment by ertrzyiks** [comment]
Totally my bad, im sorry guys. 

I have still

>Error: Cannot find module 'URIjs/src/URITemplate'

from there https://github.com/bleupen/halacious/blob/master/lib/plugin.js#L16

**Comment by bleupen** [comment]
Another release. Hopefully thats the last one.

**Comment by bleupen** [comment]
Nah it’s my bad. I should have done a global search replace. Green lights in mocha don’t always indicate functioning software :D

**Comment by clcpolevaulter** [comment]
Also, these don't seem to be getting published to the npm registry. Can you please confirm?

**Comment by clcpolevaulter** [comment]
Also, you might want to look into a lint rule for this. 

https://github.deere.com/deere-ui/deere-ui-build-tasks/blob/master/eslint_rules/no-uppercase-require.js

**Comment by bleupen** [comment]
Works for me. Is your halacious dependency in package.json compatible with 3.5.3?

**Comment by ertrzyiks** [comment]
v3.5.3 works for me as well.

**Comment by spanditcaa** [comment]
+1 on 3.5.3

**Comment by clcpolevaulter** [comment]
Yep. publish issue is on my end. Thank you so much for the immediate reply.

**Comment by clcpolevaulter** [comment]
Confirmed on my end as well. Thanks again!
