### ISSUE TITLE
multiple security issues

### ISSUE THREAD

**Issue by travi** [bleupen/halacious#93]
https://www.bithound.io/github/bleupen/halacious/master/dependencies/npm#filter-insecure-dep

it appears that releases that would include fixes are available for at least the non-dev dependencies (including jade being renamed to pug). 

could these be updated and a new release published? would a PR be helpful?

**Comment by bleupen** [comment]
Thanks for the nudge. A PR would definitely be helpful!

**Comment by travi** [comment]
to ease the burden of keeping up with updates, i've found [greenkeeper](https://greenkeeper.io/) to be very helpful

**Comment by travi** [comment]
any chance you could publish the new version. would love to clean up these issues. thanks!

**Comment by bleupen** [comment]
Yep just got back in town. Will have it out this am.

**Comment by bleupen** [comment]
published

**Comment by travi** [comment]
Thanks! Sorry, didn't mean to prod you while traveling. Appreciate getting this taken care of.
